apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-interview
spec:
  selector:
    matchLabels:
      app: devops-interview
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-interview
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: devops-interview
        image: ghcr.io/salehparsa/devops-interview:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: ["flask db upgrade; python app.py run -h 0.0.0.0"]
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "256Mi"
        volumeMounts:
        - name: config
          mountPath: ./.env
      volumes:
      - name: config
        configMap:
          name: devops-interview