apiVersion: v1
kind: Service
metadata:
  name: devops-interview-service
spec:
  selector:
    app: devops-interview
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
