apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: devops_interview_dev
  POSTGRES_USER: devops_interview_dev
  POSTGRES_PASSWORD: devops_interview_dev