name: Deploy on k8s

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Apply Database
      run: make apply-db
    - name: Apply App
      run: make apply-app